# Generated by Django 4.2.16 on 2024-10-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUFE', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('nmonto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condiciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReciboCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nmonto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField()),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_facturacion.pagoproforma')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nmonto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField()),
                ('recibo_cobro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manejador_facturacion.recibocobro')),
            ],
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='recibo_pago',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manejador_facturacion.recibopago'),
        ),
    ]
