# Generated by Django 5.1.1 on 2024-10-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0005_detallecobrocurso_detallecobroestudiante'),
        ('manejador_facturacion', '0003_remove_recibocobro_pago_pagoproforma_recibo_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocobro',
            name='estudiante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.estudiante'),
        ),
    ]
