# Generated by Django 4.2.16 on 2024-10-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CronogramaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDescuento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstudiante', models.CharField(max_length=100)),
                ('codigoEstudiante', models.CharField(max_length=50)),
                ('cursoEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInstitucion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.institucion'),
        ),
        migrations.AddField(
            model_name='cronogramaestudiante',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.estudiante'),
        ),
        migrations.AddField(
            model_name='cronogramabase',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.curso'),
        ),
    ]
