# Generated by Django 5.1.1 on 2024-10-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0003_rename_año_curso_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramabase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_cronogramas.curso'),
        ),
    ]
