# Generated by Django 5.1.1 on 2024-10-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_cronogramas', '0004_alter_cronogramabase_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCobroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCausacion', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('cronograma_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cobro', to='manejador_cronogramas.cronogramabase')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCobroEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCausacion', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('cronograma_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cobro', to='manejador_cronogramas.cronogramaestudiante')),
            ],
        ),
    ]
