# Generated by Django 4.2.16 on 2024-10-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCobroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCausacion', models.DateField()),
                ('fechaLimite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCobroEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCausacion', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('frecuencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
